from pathlib import Path

try:
    import tomllib
except ImportError:
    try:
        import tomli as tomllib  # type: ignore[no-redef]
    except ImportError:
        raise ImportError(
            "Python 3.11+ is required, or install 'tomli' for older versions: "
            "pip install tomli"
        )

CONFIG_FILENAME = "lcg.toml"

_STARTER_TOML = """\
# lcg_pipeline configuration
# Generated by: python -m lcg_pipeline build task

[project]
dir = "{project_dir}"    # exact name of the project root folder in the filesystem

[task]
dir = "{task_dir}"       # exact name of this task folder in the filesystem

# ---------------------------------------------------------------------------
# File-system paths
# Relative to the task root (where this file lives).
# Access in scripts via: pm["key"]  or  pm.path("key")
# ---------------------------------------------------------------------------
# [paths]
# raw_0  = "02 Received Files/subfolder"
# raw_1  = "02 Received Files/another_subfolder"
# proc_0 = "03_processed_data/subfolder"
# meta_0 = "03_processed_data/60_METADATA"

# ---------------------------------------------------------------------------
# Non-file sources: connection strings, API base URLs, env-var names, etc.
# Access in scripts via: pm.conn("key")
# For secrets stored in environment variables use pm.env("key") — store the
# *name* of the env variable here, not the secret itself.
# ---------------------------------------------------------------------------
# [connections]
# db_0          = "postgresql://user:pass@host/dbname"
# api_endpoint  = "https://api.example.com/v2"
# api_key_env   = "MY_API_KEY_VAR"   # pm.env("api_key_env") reads os.environ["MY_API_KEY_VAR"]
"""


def find_config(start: Path) -> Path:
    """Walk up the directory tree from *start* looking for lcg.toml."""
    for directory in [start, *start.parents]:
        candidate = directory / CONFIG_FILENAME
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        f"No '{CONFIG_FILENAME}' found in '{start}' or any parent directory. "
        f"Run 'python -m lcg_pipeline build task' in your task folder to initialise."
    )


def load_config(path: Path) -> dict:
    with open(path, "rb") as f:
        return tomllib.load(f)


def write_config(path: Path, project_dir: str, task_dir: str) -> None:
    """Write a starter lcg.toml with commented-out examples."""
    path.write_text(
        _STARTER_TOML.format(project_dir=project_dir, task_dir=task_dir),
        encoding="utf-8",
    )
