"""Directory scaffolding — Python replacement for the legacy .bat scripts."""

from pathlib import Path

from .config import write_config

HASP_URL = (
    "https://lifecyclegeocom.sharepoint.com/:f:/s/LCGServer/"
    "ErVw7I3TcpFOtJ-zIGRt45gB8YuaXpOSs9V-PFVutjbrTA?e=mURFu7"
)

# Paths relative to the project root
_BASE_DIRS = [
    "01 Project Management",
    "02 Received Files",
    "03 Technical Work/00_RDBMS",
    "03 Technical Work/01_GIS",
    "03 Technical Work/10_TASKPLACEHOLDER",
    "04 Deliverables",
    "05 Meetings",
    "06 References",
    "07 Health and Safety",
]

# Paths relative to the task folder root
_TASK_DIRS = [
    "01_scripts",
    "02_raw_data",
    "03_processed_data/60_METADATA",
    "04_figures",
    "05_models",
    "20_GIS",
    "30_phreeqc",
    "40_gwb",
    "50_gsim",
    "80_presentations",
]

_BASE_README = """\
Directory use — standard LCG project scaffolding
=================================================
01 Project Management  : PM tasks (invoices, budget, scope, etc.)
02 Received Files      : RAW data from clients and labs
                         NO MANIPULATION of data stored here.
03 Technical Work      : Task-based work (see subfolders and README inside)
04 Deliverables        : Final reports, presentations, data packages
05 Meetings            : Meeting notes, agendas, presentations
06 References          : Reference materials, papers, manuals
07 Health and Safety   : HASP and safety documents
                         Contains link to HASP SharePoint folder.
"""

_TECH_WORK_README = """\
Technical Work folder structure
================================
  00_RDBMS  Static relational database files used across tasks.
  01_GIS    Static GIS files used across tasks.
  10+       Task-specific folders.
            Rename / copy 10_TASKPLACEHOLDER:
              e.g. 11_WaterQuality, 12_GeochemModelling
            Name should be short, descriptive, and map to an AVAZA
            code where applicable.
            Run 'python -m lcg_pipeline build task' inside each task
            folder to scaffold it and generate an lcg.toml config.
"""

_TASK_README = """\
Task folder — standard LCG technical structure
===============================================
01_scripts        Analysis scripts (see 01_scripts/README.txt for conventions)
02_raw_data       Raw / extracted inputs — populate manually or via source pull
03_processed_data Outputs from scripting (see subdir README for conventions)
04_figures        Figures generated by scripts only
05_models         Trained models (.pkl, .tf, .pt, parameters) — script-populated
20_GIS            GIS work          (add 21_, 22_, ... as needed)
30_phreeqc        PHREEQC work      (add 31_, 32_, ... as needed)
40_gwb            Geochemist's WB   (add 41_, 42_, ... as needed)
50_gsim           GoldSim work      (add 51_, 52_, ... as needed)
80_presentations  Internal presentation development

lcg.toml          Pipeline config — edit to add named paths and connections.
                  Import PathManager in any script:
                    from lcg_pipeline import PathManager
                    pm = PathManager()
"""

_SCRIPTS_README = """\
Scripting structure (directory-prefix convention)
==================================================
  00_* : extract / clean / impute raw data
  01_* : exploratory data analysis (EDA)
  02_* : unsupervised learning (development)
  03_* : [placeholder / project-specific]
  04_* : supervised learning (development)
  05_* : final modelling (production)

Use scripts to create and populate directories for outputs and figures.
Import PathManager at the top of each script:

    from lcg_pipeline import PathManager
    pm = PathManager()

    # Script-named, dated output directories are created automatically:
    df.to_csv(pm.output / "results.csv")
    fig.savefig(pm.figs_out / "plot.png")
"""

_PROC_DATA_README = """\
Processed data directory structure (prefix convention)
=======================================================
  00–09      : pipeline outputs generated through scripting
               (cleaned, imputed, transformed data)
  50_DB      : formalized, static master database
  60_METADATA: cross-script metadata (see 60_METADATA/README.txt)
  60_*       : additional metadata dirs as needed
  80+        : compiled table views for reporting
"""

_METADATA_README = """\
60_METADATA — cross-script naming and aesthetic metadata
=========================================================
Stores project-wide lookup data shared across scripts: column groupings,
display names, colour palettes, marker maps, units, axis labels, etc.

Access in scripts via PathManager:
    aes  = pm.load_meta("aesthetics/colours.json")
    cols = pm.load_meta("columns/water_quality.json")

Supported formats: .json  .toml

Suggested file/folder structure
--------------------------------
columns/
    <topic>.json     Column groupings and display-name mappings.
                     Keys are internal column names; values are display labels,
                     units, groups, or dicts of those.

aesthetics/
    colours.json     Colour palettes keyed by the column used for hue.
    markers.json     Marker styles keyed by the column used for style/shape.

units.json           Unit strings keyed by column name.
                     Used for axis labels and data validation.

Template: aesthetics/colours.json
-----------------------------------
Structured for direct use with seaborn palette= arguments.
Top-level key is the DataFrame column used for the hue mapping.
{
  "site_id": {
    "MW-01": "#1f77b4",
    "MW-02": "#ff7f0e",
    "MW-03": "#2ca02c"
  },
  "analyte": {
    "NO3":  "#d62728",
    "SO4":  "#9467bd",
    "Cl":   "#8c564b"
  }
}

Usage:
    palette = aes["site_id"]
    sns.scatterplot(data=df, x="date", y="value", hue="site_id", palette=palette)

Template: aesthetics/markers.json
-----------------------------------
Structured for direct use with seaborn style= / markers= arguments.
Top-level key is the DataFrame column used for the style/shape mapping.
{
  "site_id": {
    "MW-01": "o",
    "MW-02": "s",
    "MW-03": "^"
  },
  "sample_type": {
    "grab":      "o",
    "composite": "D"
  }
}

Usage:
    markers = mrk["site_id"]
    sns.scatterplot(data=df, x="date", y="value", style="site_id", markers=markers)

Template: columns/<topic>.json
-------------------------------
{
  "pH":       { "label": "pH",           "unit": "",      "group": "field" },
  "temp_c":   { "label": "Temperature",  "unit": "°C",    "group": "field" },
  "no3_mgl":  { "label": "Nitrate",      "unit": "mg/L",  "group": "anion" }
}
"""


def _make_dirs(root: Path, dirs: list[str]) -> None:
    for rel in dirs:
        (root / rel).mkdir(parents=True, exist_ok=True)


def _write_url_shortcut(path: Path, url: str) -> None:
    path.write_text(f"[InternetShortcut]\nURL={url}\nTarget=0\n", encoding="utf-8")


def build_base(root: Path) -> None:
    """Scaffold a top-level project directory (replaces file_structure_base.bat)."""
    _make_dirs(root, _BASE_DIRS)
    (root / "README.txt").write_text(_BASE_README, encoding="utf-8")
    (root / "03 Technical Work" / "README.txt").write_text(_TECH_WORK_README, encoding="utf-8")
    _write_url_shortcut(
        root / "07 Health and Safety" / "HASP Sharepoint Link.url",
        HASP_URL,
    )
    print(f"[lcg_pipeline] Base structure created in: {root}")


def build_task(root: Path, project_dir: str, task_dir: str) -> None:
    """Scaffold a task directory and write lcg.toml (replaces file_structure_technical.bat)."""
    _make_dirs(root, _TASK_DIRS)
    (root / "README.txt").write_text(_TASK_README, encoding="utf-8")
    (root / "01_scripts" / "README.txt").write_text(_SCRIPTS_README, encoding="utf-8")
    (root / "03_processed_data" / "README.txt").write_text(_PROC_DATA_README, encoding="utf-8")
    (root / "03_processed_data" / "60_METADATA" / "README.txt").write_text(_METADATA_README, encoding="utf-8")

    config_path = root / "lcg.toml"
    write_config(config_path, project_dir, task_dir)

    print(f"[lcg_pipeline] Task structure created in: {root}")
    print(f"[lcg_pipeline] Config written to:         {config_path}")
    print(f"[lcg_pipeline] Edit lcg.toml to add named paths and connections.")
